// chapter16/blockchain/client/src/components/TransactionForm.vue
<template>
  <div>
    <h2>New transaction</h2>
    <form class="add-transaction-form" @submit.prevent="handleFormSubmit">
      <input
        type="text"
        name="sender"
        placeholder="Sender"
        autoComplete="off"
        v-model.trim="formValue.sender"
        :disabled="disabled">

      <span class="hidden-xs">→</span>

      <input
        type="text"
        name="recipient"
        placeholder="Recipient"
        autoComplete="off"
        :disabled="disabled"
        v-model.trim="formValue.recipient">

      <input
        type="number"
        name="amount"
        placeholder="Amount"
        :disabled="disabled"
        v-model.number="formValue.amount">

      <button type="submit"
              class="ripple"
              :disabled="!isValid() || disabled">
        ADD TRANSACTION
      </button>
    </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { Transaction } from '../lib/blockchain-node';

@Component
export default class TransactionForm extends Vue {

  @Prop(Boolean) readonly disabled: boolean;
  
  formValue: Transaction = this.defaultFormValue();

  isValid() {
    return (
      this.formValue.sender &&
      this.formValue.recipient &&
      this.formValue.amount > 0
    );
  }

  handleFormSubmit() {
    if (this.isValid()) {
      this.$emit('add-transaction', { ...this.formValue });

      // Reset form:
      this.formValue = this.defaultFormValue();
    }
  }

  private defaultFormValue(): Transaction {
    return {
      sender: '',
      recipient: '',
      amount: 0
    };
  }
}
</script>

// chapter13/blockchain/src/components/TransactionForm.tsx
import React, { ChangeEvent, FormEvent, useState } from 'react';
import { Transaction } from '../lib/blockchain-node';

type TransactionFormProps = {
  onAddTransaction: (transaction: Transaction) => void,
  disabled: boolean
};

const defaultFormValue = {
  recipient: '',
  sender: '',
  amount: 0
};

const TransactionForm: React.FC<TransactionFormProps> = ({ onAddTransaction, disabled }) => {
  const [formValue, setFormValue] = useState<Transaction>(defaultFormValue);
  const isValid = formValue.sender && formValue.recipient && formValue.amount > 0;

  function handleInputChange({ target }: ChangeEvent<HTMLInputElement>) {
    setFormValue({
      ...formValue,
      [target.name]: target.value
    });
  }

  function handleFormSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    onAddTransaction(formValue);
    setFormValue(defaultFormValue);
  }

  return (
    <>
      <h2>New transaction</h2>
      <form className="add-transaction-form" onSubmit={handleFormSubmit}>
        <input
          type="text"
          name="sender"
          placeholder="Sender"
          autoComplete="off"
          disabled={disabled}
          value={formValue.sender}
          onChange={handleInputChange}
        />
        <span className="hidden-xs">→</span>
        <input
          type="text"
          name="recipient"
          placeholder="Recipient"
          autoComplete="off"
          disabled={disabled}
          value={formValue.recipient}
          onChange={handleInputChange}
        />
        <input
          type="number"
          name="amount"
          placeholder="Amount"
          disabled={disabled}
          value={formValue.amount}
          onChange={handleInputChange}
        />
        <button type="submit" disabled={!isValid || disabled} className="ripple">ADD TRANSACTION</button>
      </form>
    </>
  );
}

export default TransactionForm;
