// chapter11/client/src/app/app.component.ts
import { Component } from '@angular/core';
import { Message, MessageTypes } from './shared/messages';
import { Block, BlockchainNodeService, formatTransactions, Transaction, WebsocketService } from './shared/services';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  constructor(
    private readonly server: WebsocketService,
    readonly node: BlockchainNodeService
  ) {
    this.server.messageReceived.subscribe(message => this.handleServerMessages(message));
    this.initializeBlockchain();
  }

  get statusLine(): string {
    return (
      this.node.chainIsEmpty          ? '⏳ Initializing the blockchain...' :
      this.node.isMining              ? '⏳ Mining a new block...' :
      this.node.noPendingTransactions ? '📩 Add one or more transactions.' :
                                        '✅ Ready to mine a new block.'
    );
  }

  get formattedTransactions() {
    return this.node.hasPendingTransactions
      ? formatTransactions(this.node.pendingTransactions)
      : 'No pending transactions yet.';
  }

  private async initializeBlockchain() {
    const blocks = await this.server.requestLongestChain();
    if (blocks.length > 0) {
      this.node.initializeWith(blocks);
    } else {
      await this.node.initializeWithGenesisBlock();
    }
  }

  async generateBlock(): Promise<void> {
    // Let everyone in the network know about transactions need to be added to the blockchain.
    // Every node will try to generate a new block first for the provided transactions.
    this.server.requestNewBlock(this.node.pendingTransactions);
    const miningProcessIsDone = this.node.mineBlockWith(this.node.pendingTransactions);

    const newBlock = await miningProcessIsDone;
    this.addBlock(newBlock);
  };

  private async addBlock(block: Block, notifyOthers = true): Promise<void> {
    // The addBlock() method returns a promise that is rejected if the block cannot be added
    // to the chain. Hence wrap the addBlock() call in the try / catch.
    try {
      await this.node.addBlock(block);
      if (notifyOthers) {
        this.server.announceNewBlock(block);
      }
    } catch (error) {
      console.log(error.message);
    }
  }

  handleServerMessages(message: Message) {
    switch (message.type) {
      case MessageTypes.GetLongestChainRequest: return this.handleGetLongestChainRequest(message);
      case MessageTypes.NewBlockRequest       : return this.handleNewBlockRequest(message);
      case MessageTypes.NewBlockAnnouncement  : return this.handleNewBlockAnnouncement(message);
      default: {
        console.log(`Received message of unknown type: "${message.type}"`);
      }
    }
  }

  private handleGetLongestChainRequest(message: Message): void {
    this.server.send({
      type: MessageTypes.GetLongestChainResponse,
      correlationId: message.correlationId,
      payload: this.node.chain
    });
  }

  private async handleNewBlockRequest(message: Message): Promise<void> {
    const transactions = message.payload as Transaction[];
    const newBlock = await this.node.mineBlockWith(transactions);
    this.addBlock(newBlock);
  }

  private async handleNewBlockAnnouncement(message: Message): Promise<void> {
    const newBlock = message.payload as Block;
    this.addBlock(newBlock, false);
  }
}

<main>
  <h1>Blockchain node</h1>
  <aside><p>{{ statusLine }}</p></aside>
  <section>
    <app-transaction-form></app-transaction-form>
  </section>
  <section>
    <h2>Pending transactions</h2>
    <pre class="pending-transactions__list">{{ formattedTransactions }}</pre>
    <div class="pending-transactions__form">
      <button type="button"
              class="ripple"
              (click)="generateBlock()"
              [disabled]="node.noPendingTransactions || node.isMining">GENERATE BLOCK</button>
    </div>
    <div class="clear"></div>
  </section>
  <section>
    <h2>Current blocks</h2>
    <div class="blocks">
      <div class="blocks__ribbon">
        <app-block *ngFor="let block of node.chain; let index = index"
                   [block]="block"
                   [index]="index">
        </app-block>
      </div>
      <div class="blocks__overlay"></div>
    </div>
  </section>
</main>

// chapter14/blockchain/src/components/App.tsx
import React, { useEffect, useState, useCallback } from 'react';
import { Block, BlockchainNode, Transaction } from '../lib/blockchain-node';
import { Message, MessageTypes } from '../lib/messages';
import { WebsocketController } from '../lib/websocket-controller';
import BlocksPanel from './BlocksPanel';
import PendingTransactionsPanel from './PendingTransactionsPanel';
import TransactionForm from './TransactionForm';

const server = new WebsocketController();
const node = new BlockchainNode();

const App: React.FC = () => {
  const [status, setStatus] = useState<string>('');

  const handleGetLongestChainRequest = useCallback((message: Message) => {
    server.send({
      type: MessageTypes.GetLongestChainResponse,
      correlationId: message.correlationId,
      payload: node.chain
    });
  }, []);

  const handleNewBlockRequest = useCallback(async (message: Message) => {
    const transactions = message.payload as Transaction[];
    const miningProcessIsDone = node.mineBlockWith(transactions);

    setStatus(getStatus(node));

    const newBlock = await miningProcessIsDone;
    addBlock(newBlock);
  }, []);

  const handleNewBlockAnnouncement = useCallback(async (message: Message) => {
    const newBlock = message.payload as Block;
    addBlock(newBlock, false);
  }, []);

  const handleServerMessages = useCallback((message: Message) => {
    switch (message.type) {
      case MessageTypes.GetLongestChainRequest: return handleGetLongestChainRequest(message);
      case MessageTypes.NewBlockRequest       : return handleNewBlockRequest(message);
      case MessageTypes.NewBlockAnnouncement  : return handleNewBlockAnnouncement(message);
      default: {
        console.log(`Received message of unknown type: "${message.type}"`);
      }
    }
  }, [
    handleGetLongestChainRequest,
    handleNewBlockAnnouncement,
    handleNewBlockRequest
  ]);

  useEffect(() => {
    async function initializeBlockchainNode() {
      await server.connect(handleServerMessages);
      const blocks = await server.requestLongestChain();
      if (blocks.length > 0) {
        node.initializeWith(blocks);
      } else {
        await node.initializeWithGenesisBlock();
      }
      setStatus(getStatus(node));
    }

    initializeBlockchainNode();
  }, [ handleServerMessages ]);

  useEffect(() => {
    setStatus(getStatus(node));
  }, []);

  function addTransaction(transaction: Transaction): void {
    node.addTransaction(transaction);
    setStatus(getStatus(node));
  }

  async function generateBlock() {
    // Let everyone in the network know about transactions need to be added to the blockchain.
    // Every node will try to generate a new block first for the provided transactions.
    server.requestNewBlock(node.pendingTransactions);
    const miningProcessIsDone = node.mineBlockWith(node.pendingTransactions);

    setStatus(getStatus(node));

    const newBlock = await miningProcessIsDone;
    addBlock(newBlock);
  }

  async function addBlock(block: Block, notifyOthers = true): Promise<void> {
    // The addBlock() method returns a promise that is rejected if the block cannot be added
    // to the chain. Hence wrap the addBlock() call in the try / catch.
    try {
      await node.addBlock(block);
      if (notifyOthers) {
        server.announceNewBlock(block);
      }
    } catch (error) {
      console.log(error.message);
    }

    setStatus(getStatus(node));
  }

  return (
    <main>
      <h1>Blockchain node</h1>
      <aside><p>{status}</p></aside>
      <section>
        <TransactionForm
          onAddTransaction={addTransaction}
          disabled={node.isMining || node.chainIsEmpty}
        />
      </section>
      <section>
        <PendingTransactionsPanel
          formattedTransactions={formatTransactions(node.pendingTransactions)}
          onGenerateBlock={generateBlock}
          disabled={node.isMining || node.noPendingTransactions}
        />
      </section>
      <section>
        <BlocksPanel blocks={node.chain} />
      </section>
    </main>
  );
}

function getStatus(node: BlockchainNode): string {
  return node.chainIsEmpty          ? '⏳ Initializing the blockchain...' :
         node.isMining              ? '⏳ Mining a new block...' :
         node.noPendingTransactions ? '📩 Add one or more transactions.' :
                                      '✅ Ready to mine a new block.';
}

function formatTransactions(transactions: Transaction[]): string {
  return transactions.map(t =>`${t.sender} → ${t.recipient}: $${t.amount}`).join('\n');
}

export default App;
