// chapter11/blockchain/client/src/app/transaction-form/transaction-form.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { BlockchainNodeService } from '../shared/services';

@Component({
  selector: 'app-transaction-form',
  templateUrl: './transaction-form.component.html'
})
export class TransactionFormComponent {
  readonly transactionForm: FormGroup;

  constructor(readonly node: BlockchainNodeService, fb: FormBuilder) {
    this.transactionForm = fb.group({
      sender   : ['', Validators.required],
      recipient: ['', Validators.required],
      amount   : ['', Validators.required]
    });
  }

  enqueueTransaction() {
    if (this.transactionForm.valid) {
      this.node.addTransaction(this.transactionForm.value);
      this.transactionForm.reset();
    }
  }
}

<h2>New transaction</h2>
<form class="add-transaction-form"
      [formGroup]="transactionForm"
      (ngSubmit)="enqueueTransaction()">
  <input type="text"
         name="sender"
         autocomplete="off"
         placeholder="Sender"
         formControlName="sender">

  <span class="hidden-xs">→</span>

  <input type="text"
         name="recipient"
         autocomplete="off"
         placeholder="Recipient"
         formControlName="recipient">

  <input type="number"
         name="amount"
         autocomplete="off"
         placeholder="Amount"
         formControlName="amount">

  <button type="submit"
          class="ripple"
          [disabled]="transactionForm.invalid || node.isMining">ADD TRANSACTION</button>
</form>

// chapter16/blockchain/client/src/components/TransactionForm.vue
<template>
  <div>
    <h2>New transaction</h2>
    <form class="add-transaction-form" @submit.prevent="handleFormSubmit">
      <input
        type="text"
        name="sender"
        placeholder="Sender"
        autoComplete="off"
        v-model.trim="formValue.sender"
        :disabled="disabled">

      <span class="hidden-xs">→</span>

      <input
        type="text"
        name="recipient"
        placeholder="Recipient"
        autoComplete="off"
        :disabled="disabled"
        v-model.trim="formValue.recipient">

      <input
        type="number"
        name="amount"
        placeholder="Amount"
        :disabled="disabled"
        v-model.number="formValue.amount">

      <button type="submit"
              class="ripple"
              :disabled="!isValid() || disabled">
        ADD TRANSACTION
      </button>
    </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { Transaction } from '../lib/blockchain-node';

@Component
export default class TransactionForm extends Vue {

  @Prop(Boolean) readonly disabled: boolean;
  
  formValue: Transaction = this.defaultFormValue();

  isValid() {
    return (
      this.formValue.sender &&
      this.formValue.recipient &&
      this.formValue.amount > 0
    );
  }

  handleFormSubmit() {
    if (this.isValid()) {
      this.$emit('add-transaction', { ...this.formValue });

      // Reset form:
      this.formValue = this.defaultFormValue();
    }
  }

  private defaultFormValue(): Transaction {
    return {
      sender: '',
      recipient: '',
      amount: 0
    };
  }
}
</script>
